--------------------------------------------------------
--  Fichier créé - lundi-mars-06-2023   
--------------------------------------------------------
DROP TABLE "YASSINE"."PARTENAIRE";
DROP TABLE "YASSINE"."STOCK";
--------------------------------------------------------
--  DDL for Table PARTENAIRE
--------------------------------------------------------

  CREATE TABLE "YASSINE"."PARTENAIRE" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"NUMTEL" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"QUANTITE" NUMBER, 
	"SOMME" VARCHAR2(20 BYTE), 
	"DATE_CONVENTION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STOCK
--------------------------------------------------------

  CREATE TABLE "YASSINE"."STOCK" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"QUANTITE" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into YASSINE.PARTENAIRE
SET DEFINE OFF;
Insert into YASSINE.PARTENAIRE (ID,NOM,NUMTEL,TYPE,QUANTITE,SOMME,DATE_CONVENTION) values ('5','jeuuheud',null,null,'0',null,'01/01/2000');
Insert into YASSINE.PARTENAIRE (ID,NOM,NUMTEL,TYPE,QUANTITE,SOMME,DATE_CONVENTION) values ('1','jeuuheud',null,null,'0',null,'01/01/2000');
REM INSERTING into YASSINE.STOCK
SET DEFINE OFF;
Insert into YASSINE.STOCK (ID,NOM,QUANTITE,TYPE) values ('23','banan','3','fruit');
Insert into YASSINE.STOCK (ID,NOM,QUANTITE,TYPE) values ('10','orange','40','fruit');
