--------------------------------------------------------
--  Fichier créé - lundi-mars-13-2023   
--------------------------------------------------------
DROP TABLE "YASSINE"."EMPLOYE";
DROP TABLE "YASSINE"."ENFANT";
DROP TABLE "YASSINE"."FOURNIR";
DROP TABLE "YASSINE"."HISTORY";
DROP TABLE "YASSINE"."PARTENAIRE";
DROP TABLE "YASSINE"."STOCK";
--------------------------------------------------------
--  DDL for Table EMPLOYE
--------------------------------------------------------

  CREATE TABLE "YASSINE"."EMPLOYE" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(50 BYTE), 
	"PRENOM" VARCHAR2(50 BYTE), 
	"CIN" NUMBER, 
	"DESIGNATION" VARCHAR2(50 BYTE), 
	"ADRESSE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ENFANT
--------------------------------------------------------

  CREATE TABLE "YASSINE"."ENFANT" 
   (	"ID" VARCHAR2(8 BYTE), 
	"NOM" VARCHAR2(10 BYTE), 
	"PRENOM" VARCHAR2(10 BYTE), 
	"AGE" NUMBER(10,0), 
	"DATE_DE_NAISSANCE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FOURNIR
--------------------------------------------------------

  CREATE TABLE "YASSINE"."FOURNIR" 
   (	"IDS" NUMBER, 
	"IDP" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table HISTORY
--------------------------------------------------------

  CREATE TABLE "YASSINE"."HISTORY" 
   (	"DATE_HISTORIQUE" DATE, 
	"NOMP" VARCHAR2(20 BYTE), 
	"ID" NUMBER, 
	"NOM" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PARTENAIRE
--------------------------------------------------------

  CREATE TABLE "YASSINE"."PARTENAIRE" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"NUMTEL" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"QUANTITE" NUMBER, 
	"SOMME" VARCHAR2(20 BYTE), 
	"DATE_CONVENTION" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STOCK
--------------------------------------------------------

  CREATE TABLE "YASSINE"."STOCK" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"QUANTITE" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"DATES" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into YASSINE.EMPLOYE
SET DEFINE OFF;
Insert into YASSINE.EMPLOYE (ID,NOM,PRENOM,CIN,DESIGNATION,ADRESSE) values ('123456','ERTY','BN?','123456789','AZERT','AZERTY');
Insert into YASSINE.EMPLOYE (ID,NOM,PRENOM,CIN,DESIGNATION,ADRESSE) values ('12','AZE','AZE','12','AQSD','AZER');
Insert into YASSINE.EMPLOYE (ID,NOM,PRENOM,CIN,DESIGNATION,ADRESSE) values ('12','AZE','AZE','12','AQSD','AZER');
REM INSERTING into YASSINE.ENFANT
SET DEFINE OFF;
Insert into YASSINE.ENFANT (ID,NOM,PRENOM,AGE,DATE_DE_NAISSANCE) values ('54321','arij','horchani','12',to_date('01/01/00','DD/MM/RR'));
REM INSERTING into YASSINE.FOURNIR
SET DEFINE OFF;
REM INSERTING into YASSINE.HISTORY
SET DEFINE OFF;
Insert into YASSINE.HISTORY (DATE_HISTORIQUE,NOMP,ID,NOM) values (to_date('13/03/23','DD/MM/RR'),'chouna','147','ajout');
Insert into YASSINE.HISTORY (DATE_HISTORIQUE,NOMP,ID,NOM) values (to_date('13/03/23','DD/MM/RR'),'azrtt','11','ajout');
Insert into YASSINE.HISTORY (DATE_HISTORIQUE,NOMP,ID,NOM) values (to_date('13/03/23','DD/MM/RR'),'zara','14','ajout');
Insert into YASSINE.HISTORY (DATE_HISTORIQUE,NOMP,ID,NOM) values (to_date('13/03/23','DD/MM/RR'),'azer','1454','suppression');
Insert into YASSINE.HISTORY (DATE_HISTORIQUE,NOMP,ID,NOM) values (to_date('13/03/23','DD/MM/RR'),'chouna','145','ajout');
Insert into YASSINE.HISTORY (DATE_HISTORIQUE,NOMP,ID,NOM) values (to_date('13/03/23','DD/MM/RR'),'azert','17','ajout');
Insert into YASSINE.HISTORY (DATE_HISTORIQUE,NOMP,ID,NOM) values (to_date('13/03/23','DD/MM/RR'),'chouna','147','suppression');
Insert into YASSINE.HISTORY (DATE_HISTORIQUE,NOMP,ID,NOM) values (to_date('13/03/23','DD/MM/RR'),'yassine','52','ajout');
Insert into YASSINE.HISTORY (DATE_HISTORIQUE,NOMP,ID,NOM) values (to_date('13/03/23','DD/MM/RR'),'yassine','52','suppression');
Insert into YASSINE.HISTORY (DATE_HISTORIQUE,NOMP,ID,NOM) values (to_date('13/03/23','DD/MM/RR'),'yassine','58','ajout');
REM INSERTING into YASSINE.PARTENAIRE
SET DEFINE OFF;
Insert into YASSINE.PARTENAIRE (ID,NOM,NUMTEL,TYPE,QUANTITE,SOMME,DATE_CONVENTION) values ('15','azr','5411',null,'0','4',to_date('01/01/00','DD/MM/RR'));
Insert into YASSINE.PARTENAIRE (ID,NOM,NUMTEL,TYPE,QUANTITE,SOMME,DATE_CONVENTION) values ('14','zara','+21697404777',null,'0','40',to_date('01/01/00','DD/MM/RR'));
Insert into YASSINE.PARTENAIRE (ID,NOM,NUMTEL,TYPE,QUANTITE,SOMME,DATE_CONVENTION) values ('58','yassine','+21697404777',null,'0','60',to_date('01/01/00','DD/MM/RR'));
Insert into YASSINE.PARTENAIRE (ID,NOM,NUMTEL,TYPE,QUANTITE,SOMME,DATE_CONVENTION) values ('11','azrtt','+21697404777',null,'0','40',to_date('01/01/00','DD/MM/RR'));
Insert into YASSINE.PARTENAIRE (ID,NOM,NUMTEL,TYPE,QUANTITE,SOMME,DATE_CONVENTION) values ('145','chouna','+21697404777',null,'0','40',to_date('01/01/00','DD/MM/RR'));
Insert into YASSINE.PARTENAIRE (ID,NOM,NUMTEL,TYPE,QUANTITE,SOMME,DATE_CONVENTION) values ('17','azert','+21697404777',null,'0','10',to_date('01/01/00','DD/MM/RR'));
REM INSERTING into YASSINE.STOCK
SET DEFINE OFF;
Insert into YASSINE.STOCK (ID,NOM,QUANTITE,TYPE,DATES) values ('23','banan','3','fruit',null);
Insert into YASSINE.STOCK (ID,NOM,QUANTITE,TYPE,DATES) values ('10','orange','40','fruit',null);
Insert into YASSINE.STOCK (ID,NOM,QUANTITE,TYPE,DATES) values ('5','degla','50','aefea',to_date('01/01/00','DD/MM/RR'));
Insert into YASSINE.STOCK (ID,NOM,QUANTITE,TYPE,DATES) values ('100','aaa','5','aaa',null);
Insert into YASSINE.STOCK (ID,NOM,QUANTITE,TYPE,DATES) values ('0','yass','50','yass',to_date('01/01/00','DD/MM/RR'));
--------------------------------------------------------
--  DDL for Index FOURNIR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "YASSINE"."FOURNIR_PK" ON "YASSINE"."FOURNIR" ("IDS", "IDP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PARTENAIRE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "YASSINE"."PARTENAIRE_PK" ON "YASSINE"."PARTENAIRE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index STOCK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "YASSINE"."STOCK_PK" ON "YASSINE"."STOCK" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table FOURNIR
--------------------------------------------------------

  ALTER TABLE "YASSINE"."FOURNIR" ADD CONSTRAINT "FOURNIR_PK" PRIMARY KEY ("IDS", "IDP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "YASSINE"."FOURNIR" MODIFY ("IDP" NOT NULL ENABLE);
  ALTER TABLE "YASSINE"."FOURNIR" MODIFY ("IDS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PARTENAIRE
--------------------------------------------------------

  ALTER TABLE "YASSINE"."PARTENAIRE" MODIFY ("DATE_CONVENTION" NOT NULL ENABLE);
  ALTER TABLE "YASSINE"."PARTENAIRE" MODIFY ("NUMTEL" NOT NULL ENABLE);
  ALTER TABLE "YASSINE"."PARTENAIRE" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "YASSINE"."PARTENAIRE" ADD CONSTRAINT "PARTENAIRE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "YASSINE"."PARTENAIRE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STOCK
--------------------------------------------------------

  ALTER TABLE "YASSINE"."STOCK" ADD CONSTRAINT "STOCK_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "YASSINE"."STOCK" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table FOURNIR
--------------------------------------------------------

  ALTER TABLE "YASSINE"."FOURNIR" ADD CONSTRAINT "FOURNIR_FK1" FOREIGN KEY ("IDS")
	  REFERENCES "YASSINE"."STOCK" ("ID") ENABLE;
  ALTER TABLE "YASSINE"."FOURNIR" ADD CONSTRAINT "FOURNIR_FK2" FOREIGN KEY ("IDP")
	  REFERENCES "YASSINE"."PARTENAIRE" ("ID") ENABLE;
